### ISSUE TITLE
Simplify the workflow: remove the "notebooks" directory

### ISSUE THREAD

**Issue by GaelVaroquaux** [INRIA/scikit-learn-mooc#10]
We should be able to configure jupytext so that it opens the .py files directly. That way we no longer need to the "notebooks" directory, and it's easier to keep things in sync and avoid editing the wrong files.

**Comment by GaelVaroquaux** [comment]
Confirmed: after initializing well jupytext, we can directly edit the python scripts

Initializing well jupytext requires running the following (which is not done by default):
<pre>
jupyter serverextension enable jupytext
</pre>

**Comment by ogrisel** [comment]
Sounds good to me.

It seems to work out of the box with jupyter notebook.

To make it work with "jupyter lab" (instead of "jupyter notebook"), you have to install nodejs (`conda install nodejs` works if you use conda). Then in jupyter lab you have to right click "Open with... > notebook" to open the python scripts with the notebook interface.

**Comment by GaelVaroquaux** [comment]
OK, I'll make a PR that documents this and implements the change.

Before making the PR, I need to merge all pending PRs. @lesteve @ogrisel @glemaitre : anything that I should look at?

**Comment by lesteve** [comment]
Just for completeness I plan to keep using VisualStudioCode to work on this project but yeah working inside a notebook and opening the .py with the Jupytext extension is likely the easiest thing for most people.

> Before making the PR, I need to merge all pending PRs. @lesteve @ogrisel @glemaitre : anything that I should look at?

I merged your PR and I think #6 was on a new sets of notebooks so you can go ahead and not worry about it.
