### ISSUE TITLE
Slides preview no longer working

### ISSUE THREAD

**Issue by GaelVaroquaux** [INRIA/scikit-learn-mooc#14]
The slide preview explained here: https://github.com/INRIA/scikit-learn-mooc/blob/master/slides/README.md no longer works, probably due to the change of repo.

@brospars : maybe you know how to fix that. You did the work originally

**Comment by brospars** [comment]
I'll take a look a it.

**Comment by lesteve** [comment]
So I have to admit I am note sure what @GaelVaroquaux means (probably my fault) since the link works for me:
https://inria.github.io/scikit-learn-mooc/slides/?file=ml_concepts.md...

On the other hand I was annoyed to have the CI red because of the remarkjs-pdf so I commented it out.

If you have time to look at it @brospars maybe by patching remarkjs-pdf to have a bigger timeout or using decktape to generate the PDF (as mentioned in the remark.js doc), that would be much appreciated.

**Comment by GaelVaroquaux** [comment]
OK, it does work. Maybe it was just a delay in activating github-pages for this repo (I flipped the switch, but it probably took a while to propagate). Fixed!

> On the other hand I was annoyed to have the CI red because of the remarkjs-pdf timeout so I commented it out in b92c7cf.

Should we open another issue?
