### ISSUE TITLE
Remove education-num from the kNN notebook with only numerical data

### ISSUE THREAD

**Issue by glemaitre** [INRIA/scikit-learn-mooc#166]
I think that we should remove the column `education-num` from the dataset `adult-census-num` since this is encoding a categorical variable. It would avoid some confusion since we might already introduce that `education` is a categorical variable in the first notebook.

**Comment by lesteve** [comment]
For simplicity, I am very tempted to remove `education-num` in all the notebooks after the Exploratory Data Analysis one. Basically we say `education` has the same information as `education-num` so let's remove the latter in the rest of the following notebooks.

Maybe have an extra notebook (so that I can easily skip it for the one-day starter course :stuck_out_tongue_winking_eye:) with this kind of subtleties:
- nominal vs categorical
- numerical that actually are encoding of categorical variables like `education-num`
- keeping both `education-num` and `education` since the order may had some additional information on top of the categories
