### ISSUE TITLE
Rehashing of the previous module

### ISSUE THREAD

**Issue by Phaide** [INRIA/scikit-learn-mooc#184]
In https://inria.github.io/scikit-learn-mooc/python_scripts/ensemble_introduction.html

> We recall that we need to tune these parameters, as decision trees tend to overfit the training data if we grow deep trees, but there are no rules on what each parameter should be set to. Thus, not making a search could lead us to have an underfitted or overfitted model.

This is a rehashing of the previous module, I believe we should remove this paragraph.

**Comment by glemaitre** [comment]
The previous notebook is in the module tree. This is the introduction of the ensemble module.
So it is not a big deal to make a recall. You can think that some people doing the MOOC could have a couple of days/weeks off between modules. If you are already aware, you can quickly bypass the paragraph (because it is not too long).
