### ISSUE TITLE
Dataset presentation is misplaced

### ISSUE THREAD

**Issue by LilianBoulard** [INRIA/scikit-learn-mooc#186]
The penguins dataset is presented in the "[Decision tree models](https://inria.github.io/scikit-learn-mooc/python_scripts/trees_dataset.html)" module, but was already used in a [previous chapter](https://inria.github.io/scikit-learn-mooc/python_scripts/logistic_regression.html).

I believe it should be moved earlier in the course.

I would even advise adding a chapter right after "Machine Learning concepts", presenting all the datasets we will use throughout the course (California housing, penguins, blood transfusion, etc.)

**Comment by lesteve** [comment]
Yeah probably. I would say move it where it makes the most sense for now and we will iterate afterwards where the content evolves.

I think at one point there was an idea of a presentation of all the datasets https://github.com/INRIA/scikit-learn-mooc/issues/98#issuecomment-731566292 kind of a dataset glossary so that if you don't quite remember what a dataset is all about then you can go to the dataset glossary to refresh your memory.

**Comment by lesteve** [comment]
Side-comment the label documentation feels weird not sure what you had in mind ...

**Comment by lesteve** [comment]
Feel free to create more labels if you feel there is some need.

An example label I was thinking of would be "affects MOOC platform" or something like this for things that needs a change inside the FUN MOOC platform, for example:
- some renaming of files e.g. notebook. This should be avoided for now until we tackle #151 
- change of level 1 title
- structure change e.g. moving some notebooks to a different module around

To be fair this kind of changes should probably be post-poned right now. Maybe after Gael's course (end-February) unless it is a fix and we make sure to coordinate with the Learning Lab people.
