### ISSUE TITLE
Type inconsistency between predictions (numpy array) and target (pandas Series)

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#258]
For example in https://inria.github.io/scikit-learn-mooc/python_scripts/02_numerical_pipeline_introduction.html#fit-a-model-and-make-predictions
Scroll down until:
![image](https://user-images.githubusercontent.com/1680079/111506149-a2493080-8749-11eb-8be4-e6c04d1435b3.png)

At this stage in the course I would avoid to talk about obscure technical details about `pandas` handling in scikit-learn. In practice I don't mention the discrepancy so I don't try to explain it and I never had anyone ask a question about it (I am wondering why by the way, suggestions welcome!). Maybe @glemaitre had some different experience.

Maybe we should add `.to_numpy()` when we use `predict` so that this inconsistency is less visible, at least that's my naive assumption, since it would be in the code and not in the output so easier to ignore.

Another possibility is to do `.to_numpy` on the target as we were doing at one point in the distant past.

**Comment by glemaitre** [comment]
I don't think this is a big deal right now. We are using the true and predicted target to compute some scores. Since the scikit-learn functions accept array-like, everything will be okay. Maybe a possibility would be to make a small for loop to print the first 5 predictions and true targets:

```python
for sample_idx, value in enumerate(target[:5]):
    print(f"Sample #{sample_idx} - target: {value}")
```

I would personally prefer to only add a note mentioning that `predict` and friends return a NumPy array. We do a similar explanation regarding the output of `transformer.transform` (one-hot encoder and ordinal encoder). At any point, we don't have to explain the internal indeed.

I think that if we start to use `to_numpy()`, we will have to add the above note to minimally explain why we do so.

NB: maybe in the future, scikit-learn would preserve the input type.

**Comment by lesteve** [comment]
Nobody complained about this in the forum, which I found quite surprising but still this show this is not so important for the MOOC participants ...

**Comment by lesteve** [comment]
Good enough for now
