### ISSUE TITLE
Emphasize that one should not use OneHotEncoder with tree-based models

### ISSUE THREAD

**Issue by glemaitre** [INRIA/scikit-learn-mooc#376]
I see a recurrent topic where people still want to use a `OneHotEncoder` with tree-based models in the tree module of the MOOC.
Indeed, I thought that we emphasize that one should not do that such as in this [example](https://inria.github.io/scikit-learn-mooc/python_scripts/03_categorical_pipeline_sol_02.html).

But the message is probably not strong enough. Thus, in some exercises with trees, we do not specify the type of encoding and people complain. I am not sure that we should be more explicit in the exercises but we should make sure that using a `OneHotEncoder` should be seen as a bad practice with tree-based models in general.

**Comment by ogrisel** [comment]
Note that using OHE for trees wouldn't be such a bad practice in general.  For instance lightgbm naturally support optimized handling of anti-correlated sparse features (look for "Exclusive Feature Bundling" in the lightgbm paper).

However, in the context of the scikit-learn implementation, it is almost always the case that `OrdinalEncoding` would be significantly faster than fitting a tree on dense OHE encodings.

For `HistGradientBoosting` we should mention the native categorical at some point in the feature, once they are easy to use with feature names.

**Comment by lesteve** [comment]
Maybe some kind of summary would help (not sure where, maybe a lesson-wide take-home message for the categorical data handling?). The simplified version may be something like this (but there may be some additional subtleties that we want to add):

Which encore should I use?

- OneHotEncoder: to will always do something meaningful, but can be unnecessary slow with trees
- OrdinalEncoder: can be detrimental for linear models unless your category has a meaningful order and you make sure that OrdinalEncoder respects this order. Trees can deal with OrdinalEncoder fine as long as they are deep enough.

**Comment by ArturoAmorQ** [comment]
The solution I am currently working on:

- Rephrase text in [03_categorical_pipeline.py](https://github.com/INRIA/scikit-learn-mooc/blob/master/python_scripts/03_categorical_pipeline.py) for clarity and highlight references to exercise notebooks.

- Add table and closing remarks to notebooks [03_categorical_pipeline_ex_02.py](https://github.com/INRIA/scikit-learn-mooc/blob/master/python_scripts/03_categorical_pipeline_ex_02.py) and [03_categorical_pipeline_sol_02.py](https://github.com/INRIA/scikit-learn-mooc/blob/master/python_scripts/03_categorical_pipeline_sol_02.py)


| | Meaningful order | Non-meaningful order
------------ | ------------ | ------------- 
 Tree-based model | `OrdinalEncoder` | `OrdinalEncoder`
 Linear model | `OrdinalEncoder` with caution | `OneHotEncoder`

Instead of the latter, we could make a video briefly explaining the topic. That would be a natural emphasize and harder to overlook than the notebooks.

What do you think?

**Comment by glemaitre** [comment]
Indeed, making a video should emphasise that the topic is quite important.
We could still do your propose change in the notebook first, just in case that we run out of time to make the videos since it is more time consuming.

**Comment by lesteve** [comment]
I vote for a lesson-wide text summary. Generally speaking I feel this is a bit time consuming, but this is something we could do more in other places to highlight the important things from the lesson. Also it could be a way to make sure I remember the important bits before doing the lesson quiz at the end.

I am not sure I see a good case for a video here, there is not much to show here (I do see the point about people less likely to skip a video than an exercise but a lesson-wide summary would also convey the fact that it is important) ...

**Comment by glemaitre** [comment]
Addresses in #401
