### ISSUE TITLE
Add a technical note regarding the parameter `error_score` in cross-validation tools

### ISSUE THREAD

**Issue by glemaitre** [INRIA/scikit-learn-mooc#377]
Usually, users are not digging enough to get why they obtain `NaN` with cross-validation tools (e.g. `cross_validate`). Indeed, we raise a warning but most probably, they just ignore it since this is not an error and just focus on the `NaN`.

I am usually posting that they can debug the code with `error_score="raise"` and I think that we should add this note somewhere with a concrete example.

**Comment by lesteve** [comment]
```py
from sklearn.datasets import make_classification
X, y = make_classification()

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(C='wrong-value')

from sklearn.model_selection import cross_val_score
cross_val_score(lr, X, y, n_jobs=2)
```

Side-comment: the warning is only visible with `n_jobs=1` in a notebook (probably because the warning happens in sub-processes and is not captured by the notebook server?)
![image](https://user-images.githubusercontent.com/1680079/124569080-e752b900-de45-11eb-9426-7ab23091aa93.png)

Having a warning in the main process once we check that all scores are NaNs would potentially improve the situation.

**Comment by ogrisel** [comment]
I agree this is a big usability problem.

The problem is rendered worse by the fact that the warnings on stderr can be hidden when they are raised by a loky workers. We might want to find a way to make those warnings raised by the main process instead. It would be useful both for `cross_validate`, `validation_curve`, `learning_curve`, and the `*SearchCV` meta-estimators.

**Comment by ogrisel** [comment]
@lesteve simultaneous post! I will open an issue on the scikit-learn issue tracker.

**Comment by lesteve** [comment]
Indeed 😄, good point I thought this was the scikit-learn issue tracker ...

**Comment by lesteve** [comment]
Note: as mentioned in https://github.com/scikit-learn/scikit-learn/issues/20475#issuecomment-877180157 using the latest version of `ipykernel` will show the warnings from sub-processes in the Jupyter notebook.

Updating the docker image in the JupyterHub instance to use the latest version of `ipykernel` would be a good idea too to reduce the importance of this problem.

**Comment by lesteve** [comment]
Consensus: find the first exercise where we use `cross_validate` and add a note saying that if you have warnings or only get NaN scores, you can use `error_score='raise'`.

Usability will be improved in scikit-learn 1.1 (exception is raised if all fits fail)
