### ISSUE TITLE
Consider having discussion on each page of the MOOC as edX

### ISSUE THREAD

**Issue by frcaud** [INRIA/scikit-learn-mooc#379]
Each page could have a discussion zone at the bottom:
- with a show/hide button
- containing forum post dedicated to this particular notebook or quiz

Those posts would be mirrored in the forum accessible from forum tab or in discourse.

![Screenshot from 2021-07-05 15-31-24](https://user-images.githubusercontent.com/82875602/124479037-1e718d80-dda6-11eb-95ca-8701f809b74c.png)

**Comment by lesteve** [comment]
I see how it can be useful to have everything in the same page and at the same time the technical solution seems to have one Discourse sub-category per page (or a tag per page) and it feels too granular, maybe there is a better solution though ...

Maybe something that could be in a similar spirit would be to have a "Ask question" topic in each page with a specific pattern in the title? You can use pre-filled topic https://meta.discourse.org/t/compose-a-new-pre-filled-topic-via-url/28074 for this and maybe filter on a pattern ...

Better suggestions more than welcome!

**Comment by ogrisel** [comment]
> I see how it can be useful to have everything in the same page and at the same time the technical solution seems to have one Discourse sub-category per page (or a tag per page) and it feels too granular, maybe there is a better solution though 

At the same time it might make it easier to understand the precise context of the question.

**Comment by lesteve** [comment]
@brospars not sure how hard this is, but this is definitely the most wanted feature for the second MOOC session from our side.

**Comment by brospars** [comment]
It's done on my part : https://mooc-forums.inria.fr/moocsl/categories
Waiting for it to be integrated in FUN

**Comment by lesteve** [comment]
I think what we had in mind was to have a structure like this:
- categories : modules as for session 1
- sub categories : MOOC page granularity (as you have done here)

Is that doable without too much work on your side?

The main problems I see:
- the categories page is huge vertically speaking
- there are some categories which not super useful e.g. "M2 - Module overview" (it is quite unlikely someone will have a comment about it) and I don't think they deserve their own category

Also something nice to have would be to have the module M1, M2 in the sub-categories ... just because something I found annoying in the first session is that you only get the sub-category e.g. Wrap-up quiz in the home page and you don't know before you click which module we are talking about:
![image](https://user-images.githubusercontent.com/1680079/150166372-ca5e17ef-3825-4c2a-bfd8-46d4794c9380.png)

There may be a Discourse specific way to have both categories and subcategories in Discourse in the latest page, not sure ...

**Comment by brospars** [comment]
So to summarize, we have 3 levels on the mooc : 
- Modules (vertical navigation)
- Sequences (horizontal navigation)
- Units (pages)

Since we have 2 levels of categories in Discourse, this is what I did for now : 
```
- M[X] : Sequence title
    - Unit title
```
But you wanted : 
```
- Module X
    - M[X] : Sequence title : Unit title
```
The first problem I see is that we are limited to 50 chars for the category title, so maybe we don't need the "Sequence title". @MarieCollin Have you started the integration in FUN ?

Concerning the "Module overview" categories, I agree with you but the script bulk create categories undifferentiated if it is useful or not. We can always remove it or ignore it if we don't need it.

**Comment by lesteve** [comment]
I think category/sub-category like this would be good enough:
 
- Module X: module title
    - M[X] : Unit title

**Comment by brospars** [comment]
Done ! https://mooc-forums.inria.fr/moocsl/categories

**Comment by lesteve** [comment]
Thanks! I had a quick look, that looks good to me.

**Comment by MarieCollin** [comment]
Done with automatic adds by Benoit. Verified and OK in FUN

**Comment by lesteve** [comment]
Looks good, thanks a lot! I am hoping this will help us a lot to manage the forum :crossed_fingers:
