### ISSUE TITLE
Add links to scikit-learn social networks

### ISSUE THREAD

**Issue by ArturoAmorQ** [INRIA/scikit-learn-mooc#593]
Talking with Francois we came to the idea of inviting people to follow scikit-learn social networks since the [Course presentation](https://inria.github.io/scikit-learn-mooc/) page of the mooc. This will have a positive impact on our visibility.

**Comment by GaelVaroquaux** [comment]
I think that we should:

1. Add a tiny paragraph at the bottom of the presentation page
2. Try to add on every page some social icons (jupyterbook might have an
   option for that, else it's a theming issue)
3. Add on every page a tiny note / advertisement pushing people to
   register on the MOOC on FUN

To me, point 3 is most important, because our goal is to have as many
people following the MOOC.

The note could be inserted in the bottom right of the page. This would
require a bit of css: probably using a frame, and position: fixed;
bottom: 5pt; right: 5pt, as well as the right media queries so that the
frame disappears when the screen is too small.

**Comment by GaelVaroquaux** [comment]
> 3. Add on every page a tiny note / advertisement pushing people to register on the MOOC on FUN

Actually, we already have this in our footer. It's just not very visible.

**Comment by GaelVaroquaux** [comment]
> Actually, we already have this in our footer. It's just not very visible.

I'm having a quick go at trying to make it more visible.

**Comment by lesteve** [comment]
There are some at the bottom of the page https://inria.github.io/scikit-learn-mooc/#follow-scikit-learn-on-social-networks, good enough for now.
