### ISSUE TITLE
Reconsider the use of pandas_profiling

### ISSUE THREAD

**Issue by GaelVaroquaux** [INRIA/scikit-learn-mooc#8]
The dependencies of pandas_profiling are crazy. It adds difficulty and risk to running the tutorial. Venvs are not well mastered by non experts, in particular in connections with jupyter notebooks.

**Comment by lesteve** [comment]
I agree that pandas-profiling has some "interesting" dependencies like astropy (to automatically chose the bin width for histograms IIRC). I am going to point you to a good blog post that probably says between the lines (or maybe I am reading what I want to hear) that avoiding terms like "crazy" is a good idea: http://gael-varoquaux.info/programming/technical-discussions-are-hard-a-few-tips.html :stuck_out_tongue_winking_eye:

I would be reasonably comfortable taking this risk if we have good conda install instructions.

I agree also that Jupyter kernel and conda environments might be considered too much to learn for beginners. I would suggest that binder (or the Jupyter setup in the MOOC) are probably a good way to get them started without having to install anything and that we put some emphasis on these ressources. I would say that our audience for the scikit-learn tutorials are generally at least a bit familiar with conda but we may want to reuse this material outside for more beginner-like audiences.

What we were using pandas_profiling while giving the tutorial:
- show a bit the distribution of different variables and talk a bit about different. Trying to remember more precisely which ones may help if we decide to get rid of pandas_profiling.
- point to a weird correlation between some variables (don't remember off the top of my head which one but there is a question about this in an exercise). This was useful get the point across that looking at your variables can help you identify quirks in your data and that it was useful before even thinking about doing ML.

**Comment by GaelVaroquaux** [comment]
I don't know where I stand on this issue. However, I note that I have personally a lot of friction to work on this project: it uses notebooks heavily, with the complicated machinery based on jupytext that I do not understand well, and has a lot of dependencies, which forces me to work in an environment and has resulted in user error (https://github.com/scikit-learn/scikit-learn/issues/17542).

This project complexity is at the limit of what I can personally work on: I'm task switching between dozens of projects, all with their idiosyncrasies. The setup needs simplification. We need to let go things. In particular given that the added value from a didactic standpoint of the elements that bring this complexity is very small.

**Comment by lesteve** [comment]
Yeah I am all for making it easier to get involved. You have to pick your fights and win them as a very wise person once said :wink:. It's all good in theory but I don't know how to do it in practice so we have to accept there is a little bit of trial and error there ...

I find it hard to believe that the dependency on pandas_profiling is the main bottleneck for people getting involved but I may be completely wrong.

Context:
- notebooks: so the idea was to have Python files as the source of truth and use VisualStudioCode for running them as notebooks and export them as notebook with Jupytext and rendered notebooks with nbconvert. Sometimes it is easier to work directly on the notebook (don't remember why exactly that was some feed-back from @ogrisel IIRC, maybe VisualStudioCode has improved since then I don't know ...)
- jupytext setup: less than great 100% agree. This was at the limit of my Makefile abilities I have to say (and I am sure I would not understand the Makefile if I were to look at it know). I got something half-working to at least be able to work on the materials. I am not sure Makefiles are the right tool at all to be honest, because the dependency does not only go one way with jupytext: if the paired `.py` file is more recent, the `.ipynb` will be updated but if the `.ipynb` is more recent the `.py` file will be updated.

**Comment by GaelVaroquaux** [comment]
> I find it hard to believe that the dependency on pandas_profiling is the main bottleneck for people getting involved but I may be completely wrong.

It's death by a thousands cuts: little things add up.

**Comment by glemaitre** [comment]
OK, so we gave a course with @agramfort who gave a demo of pandas-profiling. While I really like the reporting, I should say that we need to absolutely get away from it. The dependencies cannot make it usable for beginners.

We had students with Anaconda installed in general, some with a slightly outdated version. The combination of a large number of packages in the Anaconda distribution combined with outdated versions of packages (like pandas) and bad management of pandas-profiling versions in different channels (conda-forge have version 2.8; anaconda has 1.4), you get to the dark side of the python package management. And if a beginner is lucky enough to type the right instructions then the environment resolution will take 20 minutes at least which is not possible when giving the lecture in-person.

It is true that an experienced programmer can quickly workaround, installing an environment with minimum number of packages and then it will be fine. However, I think that this is not our public.

So pitifully (because I like the output of the report), I 100% backup @GaelVaroquaux with removing the report from the notebook.
We can still refer to the package because this is worth being used in advanced cases outside of the learning process in the MOOC.

This was a bit longish to explain sorry about that.

**Comment by glemaitre** [comment]
> I would be reasonably comfortable taking this risk if we have good conda install instructions.

@lesteve I only see this feasible if we create an environment from scratch where we isolate `pandas_profiling`. As I say I think this is worth having the exploration but to keep the MOOC up-to-date without breakage (on our side), we could have a notebook isolated from the rest as `a notebook to be studied on your own risk` :)

**Comment by GaelVaroquaux** [comment]
I'm glad that you are reporting what I suspected.

My experience is that it is too easy to get things wrong, when there are
many touchy dependencies. Starting from scratch with very detailed
instructions works, but it's very constraining. And chances are that
someone will do something different.

**Comment by GaelVaroquaux** [comment]
> I'm glad that you are reporting what I suspected.

Bad phrasing. I should have said: thanks for confirming.

Nothing beats first-hand field experience.

**Comment by glemaitre** [comment]
> Bad phrasing. I should have said: thanks for confirming.

:) I think that things got worse recently with the new pandas release indeed. I don't recall as much trouble in the previous session before pandas 1.0

**Comment by GaelVaroquaux** [comment]
> I think that things got worse recently with the new pandas release indeed. I don't recall as much trouble in the previous session before pandas 1.0

But that's the point of the problem with dependencies: they create a
liability on something that you do not control. The more the
dependencies, the more the landscape will change.

**Comment by agramfort** [comment]
pb is that pandas_profiling has added a crazy list of hard
dependencies recently with a lot of jupyter stuff etc.

https://github.com/pandas-profiling/pandas-profiling/blob/master/requirements.txt

**Comment by lesteve** [comment]
Each time @GaelVaroquaux is right one more time I am slightly annoyed, it's like your parents "I told you so" kind of thing? Can we ask the universe to prove him wrong from time to time :upside_down_face: ?

So here are the main two options I see:
- replace pandas-profiling by plots with pandas/seaborn/matplotlib and mention pandas-profiling as a nice tool to try out. I think the main thing is to remember the things we were highlighting in pandas-profiling report: probably browsing through univariate plots, highlighting the fact that capital-gain and capital-loss had a lot of zeroes, talking about duplicated rows, and the weird correlation between the two variables we mention in one of the exercise, anything else?
- save a HTML report in the repo and load it in the notebook. The risk is that they go out of sync with the dataset but I guess it is not that likely?

**Comment by GaelVaroquaux** [comment]
Don't worry, I'm wrong plenty of times too, and happy to admit it.

I'd rather go for option 1, because I fear that pushing beginners to
install pandas-profiling raises the danger that they do something wrong.

**Comment by lesteve** [comment]
> Don't worry, I'm wrong plenty of times too, and happy to admit it.

That's reassuring somehow :wink:.

Note that option 2. would not require users to install pandas-profiling. We would have the HTML report in the repo and load it in the notebook inside an iframe (the same way we were loading the openml dataset web page and removed it eventually) but you may not like this option either because there is a bit of magic code to show the HTML ...

**Comment by GaelVaroquaux** [comment]
Option 2 would save our problem for this specific data, but it would not
give to users a way to apply the process to new data without installing
pandas-profiling. This was the meaning of my fear.

**Comment by agramfort** [comment]
maybe worth having this discussion with pandas-profilng devs who might be
pragmatic people...

>

**Comment by GaelVaroquaux** [comment]
> maybe worth having this discussion with pandas-profilng devs who might be pragmatic people...

Maybe. But, I put an issue to point out they were modifying globals (matplotlib rcParams) on import, which breaks things. They replied that they wouldn't do the effort of fixing it themselves.

This is an effort to do a MOOC on scikit-learn, and we are going quite off track: if we try to rely on minor packages with liabilities and to fix these, we are not making progress on our objectives.

**Comment by agramfort** [comment]
choose your battles :)
